/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolsystem;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author codeGeek
 */
public class Dashboard extends javax.swing.JFrame {
 static String role;
    DatabaseConnect dbconn;
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    private String teacher_name;
    private static String username;
 

    Dashboard(String role,String username) {
              initComponents();
              this.setIconImage(new ImageIcon("C:\\Users\\codeGeek\\Documents\\NetBeansProjects"
                      + "\\SchoolSystem\\src\\schoolsystem\\images\\schoolicon.jpg").getImage());
        try {
         dbconn=new DatabaseConnect();
         conn=dbconn.dbConnect();
         this.username=username;
         if(role.equals("teacher")){
            btn_marks.setEnabled(true);
            btn_main_module.setEnabled(false);
            btn_fee_module.setEnabled(false);
         }
         else{
          btn_marks.setEnabled(false);
          }
         //To change body of generated methods, choose Tools | Templates.
     } catch (ClassNotFoundException ex) {
         Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
     } catch (SQLException ex) {
         Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
     }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_reports = new javax.swing.JButton();
        btn_main_module = new javax.swing.JButton();
        btn_fee_module = new javax.swing.JButton();
        btn_marks = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("School Dashboard");
        setResizable(false);

        btn_reports.setText("Reports");
        btn_reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportsActionPerformed(evt);
            }
        });

        btn_main_module.setText("Main Module");
        btn_main_module.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_main_moduleActionPerformed(evt);
            }
        });

        btn_fee_module.setText("Fee module");
        btn_fee_module.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fee_moduleActionPerformed(evt);
            }
        });

        btn_marks.setText("Teacher Marks");
        btn_marks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_marksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_main_module)
                    .addComponent(btn_fee_module))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_marks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_reports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_main_module)
                    .addComponent(btn_reports))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_fee_module)
                    .addComponent(btn_marks))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Signout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_reportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportsActionPerformed
       new ReportModule().setVisible(true);
    }//GEN-LAST:event_btn_reportsActionPerformed

    private void btn_main_moduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_main_moduleActionPerformed
    
                         
        new StudentMainModule(username).setVisible(true);
       
    }//GEN-LAST:event_btn_main_moduleActionPerformed

    private void btn_marksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_marksActionPerformed
         String idno=showInputDialog(); 
         if(idno==null){
             
         }
         else{
         String tName = ValidateIdno(idno);
       if(  tName==null){
           JOptionPane.showMessageDialog(null, "UnRecognized id");              
       }
       else {
           //close();
        new MarksEntrydialog(tName,idno).setVisible(true);
       }
         }         
    }//GEN-LAST:event_btn_marksActionPerformed

    private void btn_fee_moduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fee_moduleActionPerformed
      new FeeModule().setVisible(true);
    }//GEN-LAST:event_btn_fee_moduleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       new LoginForm().setVisible(true);
       close();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
                new Dashboard(role,username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_fee_module;
    private javax.swing.JButton btn_main_module;
    private javax.swing.JButton btn_marks;
    private javax.swing.JButton btn_reports;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void close(){ 
        WindowEvent event=new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(event);
         //To change body of generated methods, choose Tools | Templates.
    } //To change body of generated methods, choose Tools | Templates.

    private String showInputDialog() {
        String inputValue=JOptionPane.showInputDialog(null, "Enter Tsc  no","Teacher verification",JOptionPane.PLAIN_MESSAGE);
     if(JOptionPane.OK_OPTION==1){
        if(!inputValue.matches("[0-9]*")||inputValue.isEmpty()||inputValue==null){
        inputValue=showInputDialog();
     }
        
     }
     else{
         
     }
     
        return inputValue;
     
    }

    private String ValidateIdno(String idno) {
     try {
         String teachername="Select surname,firstname,lastname from teacher where tscNo='"+idno+"'";
         pst=conn.prepareStatement(teachername);
         rs=pst.executeQuery();    
         if(rs.next()){
            teacher_name=rs.getString("firstname")+" "+rs.getString("surname");
         }
         //To change body of generated methods, choose Tools | Templates.
     } catch (SQLException ex) {
         Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
     }
     return teacher_name;
    }
   
   
}
