/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolsystem;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author codeGeek
 */
public class StudentPromption extends javax.swing.JDialog {
    DatabaseConnect dbconn;
    Connection conn=null;
    PreparedStatement pst=null;
    /**
     * Creates new form StudentPromption
     */
    public StudentPromption(JFrame frame,boolean  modal) {
        super(frame, modal);
        initComponents();
        try{
            dbconn=new DatabaseConnect();
            conn=dbconn.dbConnect();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DeleteStudent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DeleteStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_promote = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();

        setResizable(false);

        btn_promote.setText("Move");
        btn_promote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_promoteActionPerformed(evt);
            }
        });

        jLabel1.setText("Click to promote all student");

        btn_exit.setText("Exit");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_exit)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_promote)
                        .addGap(8, 8, 8)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_promote)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_exit)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_promoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_promoteActionPerformed
       btn_promote.setEnabled(false);
       promoteForm4();       
       promoteform3();
       promoteform2();
       promoteform1();
    
    }//GEN-LAST:event_btn_promoteActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
   WindowEvent event=new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(event);
    }//GEN-LAST:event_btn_exitActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_promote;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void promoteForm4() {
    try {
        String update="update student set year=?, completion=? where year=?";
         
        pst=conn.prepareStatement(update);
        pst.setInt(1, 5);
        pst.setString(2, new SimpleDateFormat("yyyy").format(new Date()));
        pst.setInt(3, 4);  pst.executeUpdate();
        
        
        //To change body of generated methods, choose Tools | Templates.
    } catch (SQLException ex) {
        Logger.getLogger(StudentPromption.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    private void promoteform3() {
      try {
        String update="update student set year=? where  year=?";
         
        pst=conn.prepareStatement(update);
        pst.setInt(1, 4);
        pst.setInt(2, 3);  pst.executeUpdate();
        
        
        //To change body of generated methods, choose Tools | Templates.
    } catch (SQLException ex) {
        Logger.getLogger(StudentPromption.class.getName()).log(Level.SEVERE, null, ex);
    } //To change body of generated methods, choose Tools | Templates.
    }

    private void promoteform2() {
        try {
        String update="update student set year=? where year=?";
         
        pst=conn.prepareStatement(update);
        pst.setInt(1, 3);
        pst.setInt(2, 2);
          pst.executeUpdate();
        
        
        //To change body of generated methods, choose Tools | Templates.
    } catch (SQLException ex) {
        Logger.getLogger(StudentPromption.class.getName()).log(Level.SEVERE, null, ex);
    } //To change body of generated methods, choose Tools | Templates.
    }

    private void promoteform1() {
      try {
        String update="update student set year=? where year=?";
         
        pst=conn.prepareStatement(update);
        pst.setInt(1, 2);
        pst.setInt(2, 1);
        pst.executeUpdate();
        
        //To change body of generated methods, choose Tools | Templates.
    } catch (SQLException ex) {
        Logger.getLogger(StudentPromption.class.getName()).log(Level.SEVERE, null, ex);
    } //To change body of generated methods, choose Tools | Templates.
    }

    private void close() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
