/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolsystem;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author codeGeek
 */
public class TeacherList extends javax.swing.JDialog {
    
    DatabaseConnect dbcon=null;
    Connection conn=null;
    PreparedStatement pst=null;
     private ResultSet rs; 
    private String idno;
    private UpdateTeacherDialog teacherUpadate;
    private String tsno;
    private String firstname;
    private String lastname;
    private String report_source;
    private String sujects;
    private String mobileno;
    private String email;
    /**
     * Creates new form TeacherList
     */
    public TeacherList(JFrame frame,boolean b) {
        super(frame, b);
        try {
            initComponents();
          
            dbcon=new DatabaseConnect();
            conn=dbcon.dbConnect();
              retrieveAllTeachers();
            updateTabl();
            
                
          
             
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TeacherList.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TeacherList.class.getName()).log(Level.SEVERE, null, ex);
        }
 
    }

    public void update(){
       
                        retrieveAllTeachers();
                        updateTabl();
                        //To change body of generated methods, choose Tools | Templates.
                   
    }
public void retrieveAllTeachers(){
        try {
            String allTeachers="select tscno as TscNO,id_no as IdNo,firstname,lastname,surname,subject,mobile_no as MobileNo,email from teacher";
            pst=conn.prepareStatement(allTeachers);
            rs=pst.executeQuery();           
                table_teacherlist.setModel(new ResultSetTableModel(rs));
              
        }
        catch (SQLException ex) {
            Logger.getLogger(TeacherList.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_update = new javax.swing.JButton();
        btn_add_new = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_teacherlist = new javax.swing.JTable();
        btn_delete = new javax.swing.JButton();
        btn_generate_report = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("List of Teachers ");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Teacher's list"));

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_add_new.setText("Add new");
        btn_add_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_newActionPerformed(evt);
            }
        });

        table_teacherlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_teacherlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_teacherlistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_teacherlist);

        btn_delete.setText("Delete Teacher");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_generate_report.setText("Generate Report");
        btn_generate_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generate_reportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_delete)
                    .addComponent(btn_update)
                    .addComponent(btn_add_new)
                    .addComponent(btn_generate_report))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btn_delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_add_new)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_generate_report))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void table_teacherlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_teacherlistMouseClicked
            btn_add_new.setEnabled(true);
            btn_delete.setEnabled(true);
            btn_update.setEnabled(true);
            int row=table_teacherlist.getSelectedRow();
            tsno = table_teacherlist.getModel().getValueAt(row, 0).toString();
            idno = table_teacherlist.getModel().getValueAt(row, 1).toString();
            firstname= table_teacherlist.getModel().getValueAt(row, 2).toString();
            lastname = table_teacherlist.getModel().getValueAt(row, 3).toString();
            report_source = table_teacherlist.getModel().getValueAt(row, 4).toString();
            sujects = table_teacherlist.getModel().getValueAt(row, 5).toString();
            mobileno = table_teacherlist.getModel().getValueAt(row, 6).toString();
            email=table_teacherlist.getModel().getValueAt(row, 7).toString();
    }//GEN-LAST:event_table_teacherlistMouseClicked

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        int confirm=JOptionPane.showConfirmDialog(null, "Delete Teacher?", "Confirm Delete", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(confirm==JOptionPane.OK_OPTION){
        try {
            String delete_teacher="delete from teacher where id_no='"+idno+"'";
            pst=conn.prepareStatement(delete_teacher);
            if(  pst.executeUpdate()>0){
                JOptionPane.showMessageDialog(null, "Teacher Deletion Successfull");
                retrieveAllTeachers();
                updateTabl();
            }  } catch (SQLException ex) {
            Logger.getLogger(TeacherList.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else{
            JOptionPane.showMessageDialog(null, "No deletion done");
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
      retrieveAllTeachers();
        teacherUpadate=new UpdateTeacherDialog(firstname,lastname,report_source,idno,mobileno,email,this,true);
       teacherUpadate.setVisible(true);
       
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_add_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_newActionPerformed
   TeacherReg teacher_reg=new TeacherReg(this, true);
       teacher_reg.setVisible(true);
    }//GEN-LAST:event_btn_add_newActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    update();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_generate_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generate_reportActionPerformed

        try {
            
            String report_source=("C:\\Users\\codeGeek\\Documents\\NetBeansProjects\\SchoolSystem\\src\\schoolsystem\\reports\\teacherList.jrxml");
            JasperReport jr= JasperCompileManager.compileReport(report_source);
            JasperPrint jp= JasperFillManager.fillReport(jr, null,conn);
            JasperViewer viewer=new JasperViewer(jp,false);
            viewer.setTitle("List of Teachers");
            //viewer.setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\codeGeek\\Documents\\NetBeansProjects\\SchoolSystem\\src\\schoolsystem\\images\\report.jpg"));
            JDialog dialog = new JDialog(this);//the owner
            dialog.setContentPane(viewer.getContentPane());
            dialog.setSize(viewer.getSize());
            dialog.setTitle("Teacher's List");
            dialog.setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\codeGeek\\Documents\\NetBeansProjects\\SchoolSystem\\src\\schoolsystem\\images\\report.jpg") );
            dialog.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(TeacherList.class.getName()).log(Level.SEVERE, null, ex);
        }
          
          
     
    }//GEN-LAST:event_btn_generate_reportActionPerformed

    /**
     * @param args the command line arguments
     */
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_new;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_generate_report;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_teacherlist;
    // End of variables declaration//GEN-END:variables

    private void updateTabl() {
      if(table_teacherlist.getModel().getRowCount()>0){
          table_teacherlist.setRowSelectionInterval(0, 0);
           
            btn_delete.setEnabled(true);
            btn_update.setEnabled(true);
            btn_generate_report.setEnabled(true);}
        else{
        
            btn_delete.setEnabled(false);
            btn_update.setEnabled(false);
            btn_generate_report.setEnabled(false);}//To change body of generated methods, choose Tools | Templates.
    }
}
